# generators/report_builder.py
from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from analyzers.schema_analyzer import SchemaInfo
from analyzers.causal_engine import CausalRelationship, HealthScore
from config import config


class ReportBuilder:
    """
    Assembles all analysis outputs into multiple report formats:
    - JSON  : Complete machine-readable master report
    - MD    : Human-readable data dictionary (Markdown)
    - YAML  : Per-table executable data contracts
    - JSON  : Health score summary
    """

    def __init__(self, output_dir: str = None):
        self.output_dir = Path(output_dir or config.OUTPUT_DIR)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    def build_all(
        self,
        schema: SchemaInfo,
        er_summary: Dict,
        quality_metrics: Dict,
        ai_schema_summary: str,
        table_summaries: Dict[str, str],
        causal_relationships: List[CausalRelationship],
        health_scores: Dict[str, HealthScore],
        data_contracts: Dict[str, str],
        drift_report: Dict = None,
    ) -> str:
        """Write all reports to disk. Returns output directory path."""

        paths = {}

        # 1. Master JSON report
        paths["json"] = self._write_master_json(
            schema, er_summary, quality_metrics,
            ai_schema_summary, table_summaries,
            causal_relationships, health_scores, drift_report
        )

        # 2. Markdown data dictionary
        paths["markdown"] = self._write_markdown_dict(
            schema, table_summaries, quality_metrics, health_scores
        )

        # 3. Data contracts (one YAML file per table)
        contracts_dir = self.output_dir / "data_contracts"
        contracts_dir.mkdir(exist_ok=True)
        for table_name, yaml_str in data_contracts.items():
            path = contracts_dir / f"{table_name}_contract.yaml"
            path.write_text(yaml_str, encoding="utf-8")
        paths["contracts"] = str(contracts_dir)

        # 4. Health scores JSON
        paths["health"] = self._write_health_scores(health_scores)

        # 5. Schema snapshot (for future drift detection)
        paths["snapshot"] = self._write_schema_snapshot(schema)

        return str(self.output_dir)

    # ── File Writers ──────────────────────────────────────────────────────────

    def _write_master_json(
        self, schema, er_summary, quality_metrics,
        ai_summary, table_summaries,
        causal_rels, health_scores, drift_report
    ) -> str:
        data = {
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "generator": "DB Intelligence Agent v1.0",
                "database": schema.db_display_name,
                "total_tables": schema.total_tables,
                "total_columns": schema.total_columns,
                "total_rows": schema.total_rows,
            },
            "ai_schema_summary": ai_summary,
            "er_structure": er_summary,
            "table_summaries": table_summaries,
            "data_quality": quality_metrics,
            "causal_relationships": [r.to_dict() for r in causal_rels],
            "health_scores": {
                t: h.to_dict() for t, h in health_scores.items()
            },
            "drift_report": drift_report or {},
        }
        path = self.output_dir / f"db_analysis_{self.timestamp}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str, ensure_ascii=False)
        return str(path)

    def _write_markdown_dict(
        self, schema, table_summaries, quality_metrics, health_scores
    ) -> str:
        lines = [
            "# 📖 Data Dictionary",
            f"*Generated by DB Intelligence Agent — {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
            "",
            f"**Database:** `{schema.db_display_name}`  ",
            f"**Tables:** {schema.total_tables}  ",
            f"**Total Columns:** {schema.total_columns}  ",
            f"**Total Rows:** {schema.total_rows:,}",
            "",
            "---",
            "",
            "## 📊 Table Index",
            "",
            "| Table | Rows | Columns | Completeness | Health |",
            "|-------|------|---------|-------------|--------|",
        ]

        for t_name, t_info in schema.tables.items():
            q = quality_metrics.get(t_name, {})
            h = health_scores.get(t_name)
            comp = f"{q.get('overall_completeness', 0):.1%}"
            health_str = f"{h.icon} {h.label} ({h.score})" if h else "—"
            lines.append(
                f"| `{t_name}` | {t_info.row_count:,} | "
                f"{len(t_info.columns)} | {comp} | {health_str} |"
            )

        lines += ["", "---", ""]

        for t_name, t_info in schema.tables.items():
            h = health_scores.get(t_name)
            health_badge = f"{h.icon} {h.label}" if h else ""

            lines += [
                f"## 📦 `{t_name}` {health_badge}",
                "",
                f"**Rows:** {t_info.row_count:,}  |  "
                f"**Columns:** {len(t_info.columns)}  |  "
                f"**PKs:** {', '.join(f'`{k}`' for k in t_info.primary_keys) or 'None'}",
                "",
            ]

            # AI summary
            summary = table_summaries.get(t_name, "")
            if "BUSINESS PURPOSE:" in summary:
                bp = summary.split("BUSINESS PURPOSE:")[-1].split("COLUMNS:")[0].strip()
                lines += [f"> {bp}", ""]

            if h:
                lines += [
                    f"**⚕️ Health Score:** {h.score}/100 — {h.recommendation}",
                    "",
                ]

            # Column table
            lines += [
                "| Column | Type | PK | FK | Nullable | Null Rate | Notes |",
                "|--------|------|----|----|----------|-----------|-------|",
            ]

            q_cols = quality_metrics.get(t_name, {}).get("columns", {})
            for col in t_info.columns:
                null_rate = q_cols.get(col.name, {}).get("null_rate", "—")
                null_rate_str = (
                    f"{null_rate:.1%}" if isinstance(null_rate, float) else str(null_rate)
                )
                pk = "✅" if col.is_primary_key else ""
                fk = f"→ `{col.references_table}.{col.references_column}`" if col.is_foreign_key else ""
                nullable = "Yes" if col.nullable else "No"

                lines.append(
                    f"| `{col.name}` | `{col.data_type}` | {pk} | {fk} | "
                    f"{nullable} | {null_rate_str} |  |"
                )

            lines += ["", ""]

        path = self.output_dir / f"data_dictionary_{self.timestamp}.md"
        path.write_text("\n".join(lines), encoding="utf-8")
        return str(path)

    def _write_health_scores(self, health_scores: Dict[str, HealthScore]) -> str:
        data = {t: h.to_dict() for t, h in health_scores.items()}
        path = self.output_dir / f"health_scores_{self.timestamp}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        return str(path)

    def _write_schema_snapshot(self, schema: SchemaInfo) -> str:
        snapshot = {
            "snapshot_at": datetime.now().isoformat(),
            "tables": {
                name: {
                    "column_names": [c.name for c in table.columns],
                    "primary_keys": table.primary_keys,
                    "row_count": table.row_count,
                }
                for name, table in schema.tables.items()
            },
        }
        path = self.output_dir / "schema_snapshot_latest.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(snapshot, f, indent=2)
        return str(path)

    def get_markdown_dict(
        self, schema, table_summaries, quality_metrics, health_scores
    ) -> str:
        """Return markdown content as string (used by Streamlit dashboard)."""
        builder = ReportBuilder.__new__(ReportBuilder)
        builder.output_dir = self.output_dir
        builder.timestamp = self.timestamp
        lines = []
        # Reuse the same logic but return string
        tmp_path = self.output_dir / "_tmp_dict.md"
        self._write_markdown_dict(schema, table_summaries, quality_metrics, health_scores)
        # Just rebuild in memory for return
        return "\n".join([
            f"# Data Dictionary — `{schema.db_display_name}`",
            f"*{schema.total_tables} tables · {schema.total_columns} columns · {schema.total_rows:,} rows*",
        ])